/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se;

/**
 *
 * @author adolfo
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoP1 = new javax.swing.ButtonGroup();
        grupoP2 = new javax.swing.ButtonGroup();
        grupoP3 = new javax.swing.ButtonGroup();
        grupoP4 = new javax.swing.ButtonGroup();
        grupoP5 = new javax.swing.ButtonGroup();
        grupoP6 = new javax.swing.ButtonGroup();
        grupoP7 = new javax.swing.ButtonGroup();
        grupoP8 = new javax.swing.ButtonGroup();
        grupoP9 = new javax.swing.ButtonGroup();
        grupoP10 = new javax.swing.ButtonGroup();
        grupoP11 = new javax.swing.ButtonGroup();
        grupoP12 = new javax.swing.ButtonGroup();
        panelPreguntas = new javax.swing.JPanel();
        etP1 = new javax.swing.JLabel();
        opcionP1Si = new javax.swing.JRadioButton();
        opcionP1No = new javax.swing.JRadioButton();
        opcionP1NA = new javax.swing.JRadioButton();
        etP2 = new javax.swing.JLabel();
        opcionP2Si = new javax.swing.JRadioButton();
        opcionP2No = new javax.swing.JRadioButton();
        opcionP2NA = new javax.swing.JRadioButton();
        etP3 = new javax.swing.JLabel();
        opcionP3Si = new javax.swing.JRadioButton();
        opcionP3No = new javax.swing.JRadioButton();
        opcionP3NA = new javax.swing.JRadioButton();
        etP4 = new javax.swing.JLabel();
        opcionP4Si = new javax.swing.JRadioButton();
        opcionP4No = new javax.swing.JRadioButton();
        opcionP4NA = new javax.swing.JRadioButton();
        etP5 = new javax.swing.JLabel();
        opcionP5Si = new javax.swing.JRadioButton();
        opcionP5No = new javax.swing.JRadioButton();
        opciónP5NA = new javax.swing.JRadioButton();
        etP6 = new javax.swing.JLabel();
        opcionP6Si = new javax.swing.JRadioButton();
        opcionP6No = new javax.swing.JRadioButton();
        opcionP6NA = new javax.swing.JRadioButton();
        etP7 = new javax.swing.JLabel();
        opcionP7Si = new javax.swing.JRadioButton();
        opcionP7No = new javax.swing.JRadioButton();
        opcionP7NA = new javax.swing.JRadioButton();
        etP8 = new javax.swing.JLabel();
        opcionP8Si = new javax.swing.JRadioButton();
        opcionP8No = new javax.swing.JRadioButton();
        opcionP8NA = new javax.swing.JRadioButton();
        etP9 = new javax.swing.JLabel();
        opcionP9Si = new javax.swing.JRadioButton();
        opcionP9No = new javax.swing.JRadioButton();
        opcionP9NA = new javax.swing.JRadioButton();
        etP10 = new javax.swing.JLabel();
        opcionP10Si = new javax.swing.JRadioButton();
        opcionP10No = new javax.swing.JRadioButton();
        opcionP10NA = new javax.swing.JRadioButton();
        etP11 = new javax.swing.JLabel();
        opcionP11Si = new javax.swing.JRadioButton();
        opcionP11No = new javax.swing.JRadioButton();
        opcionP11NA = new javax.swing.JRadioButton();
        etP12 = new javax.swing.JLabel();
        opcionP12Si = new javax.swing.JRadioButton();
        opcionP12No = new javax.swing.JRadioButton();
        opcionP12NA = new javax.swing.JRadioButton();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonRespuesta = new javax.swing.JButton();
        botonLimpiarOpciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etP1.setText("jLabel1");

        grupoP1.add(opcionP1Si);
        opcionP1Si.setText("Si");

        grupoP1.add(opcionP1No);
        opcionP1No.setText("No");

        grupoP1.add(opcionP1NA);
        opcionP1NA.setText("Sin relevancia");

        etP2.setText("jLabel1");

        grupoP2.add(opcionP2Si);
        opcionP2Si.setText("Si");

        grupoP2.add(opcionP2No);
        opcionP2No.setText("No");

        grupoP2.add(opcionP2NA);
        opcionP2NA.setText("Sin relevancia");

        etP3.setText("jLabel1");

        grupoP3.add(opcionP3Si);
        opcionP3Si.setText("Si");

        grupoP3.add(opcionP3No);
        opcionP3No.setText("No");

        grupoP3.add(opcionP3NA);
        opcionP3NA.setText("Sin relevancia");

        etP4.setText("jLabel1");

        grupoP4.add(opcionP4Si);
        opcionP4Si.setText("Si");

        grupoP4.add(opcionP4No);
        opcionP4No.setText("No");

        grupoP4.add(opcionP4NA);
        opcionP4NA.setText("Sin relevancia");

        etP5.setText("jLabel1");

        grupoP5.add(opcionP5Si);
        opcionP5Si.setText("Si");

        grupoP5.add(opcionP5No);
        opcionP5No.setText("No");

        grupoP5.add(opciónP5NA);
        opciónP5NA.setText("Sin relevancia");

        etP6.setText("jLabel1");

        grupoP6.add(opcionP6Si);
        opcionP6Si.setText("Si");

        grupoP6.add(opcionP6No);
        opcionP6No.setText("No");

        grupoP6.add(opcionP6NA);
        opcionP6NA.setText("Sin relevancia");

        etP7.setText("jLabel1");

        grupoP7.add(opcionP7Si);
        opcionP7Si.setText("Si");

        grupoP7.add(opcionP7No);
        opcionP7No.setText("No");

        grupoP7.add(opcionP7NA);
        opcionP7NA.setText("Sin relevancia");

        etP8.setText("jLabel1");

        grupoP8.add(opcionP8Si);
        opcionP8Si.setText("Si");

        grupoP8.add(opcionP8No);
        opcionP8No.setText("No");

        grupoP8.add(opcionP8NA);
        opcionP8NA.setText("Sin relevancia");

        etP9.setText("jLabel1");

        grupoP9.add(opcionP9Si);
        opcionP9Si.setText("Si");

        grupoP9.add(opcionP9No);
        opcionP9No.setText("No");

        grupoP9.add(opcionP9NA);
        opcionP9NA.setText("Sin relevancia");

        etP10.setText("jLabel1");

        grupoP10.add(opcionP10Si);
        opcionP10Si.setText("Si");

        grupoP10.add(opcionP10No);
        opcionP10No.setText("No");

        grupoP10.add(opcionP10NA);
        opcionP10NA.setText("Sin relevancia");

        etP11.setText("jLabel1");

        grupoP11.add(opcionP11Si);
        opcionP11Si.setText("Si");

        grupoP11.add(opcionP11No);
        opcionP11No.setText("No");

        grupoP11.add(opcionP11NA);
        opcionP11NA.setText("Sin relevancia");

        etP12.setText("jLabel1");

        grupoP12.add(opcionP12Si);
        opcionP12Si.setText("Si");

        grupoP12.add(opcionP12No);
        opcionP12No.setText("No");

        grupoP12.add(opcionP12NA);
        opcionP12NA.setText("Sin relevancia");

        javax.swing.GroupLayout panelPreguntasLayout = new javax.swing.GroupLayout(panelPreguntas);
        panelPreguntas.setLayout(panelPreguntasLayout);
        panelPreguntasLayout.setHorizontalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP1Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP1No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP1NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP2Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP2No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP2NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP3Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP3No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP3NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP4, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP4Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP4No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP4NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP5, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP5Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP5No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opciónP5NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP6, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP6Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP6No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP6NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP7, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP7Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP7No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP7NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP8, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP8Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP8No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP8NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP9, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP9Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP9No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP9NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP10, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP10Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP10No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP10NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP11, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP11Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP11No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP11NA))
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addComponent(etP12, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP12Si)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP12No)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionP12NA))
        );
        panelPreguntasLayout.setVerticalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP1)
                    .addComponent(opcionP1Si)
                    .addComponent(opcionP1No)
                    .addComponent(opcionP1NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP2)
                    .addComponent(opcionP2Si)
                    .addComponent(opcionP2No)
                    .addComponent(opcionP2NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP3)
                    .addComponent(opcionP3Si)
                    .addComponent(opcionP3No)
                    .addComponent(opcionP3NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP4)
                    .addComponent(opcionP4Si)
                    .addComponent(opcionP4No)
                    .addComponent(opcionP4NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP5)
                    .addComponent(opcionP5Si)
                    .addComponent(opcionP5No)
                    .addComponent(opciónP5NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP6)
                    .addComponent(opcionP6Si)
                    .addComponent(opcionP6No)
                    .addComponent(opcionP6NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP7)
                    .addComponent(opcionP7Si)
                    .addComponent(opcionP7No)
                    .addComponent(opcionP7NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP8)
                    .addComponent(opcionP8Si)
                    .addComponent(opcionP8No)
                    .addComponent(opcionP8NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP9)
                    .addComponent(opcionP9Si)
                    .addComponent(opcionP9No)
                    .addComponent(opcionP9NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP10)
                    .addComponent(opcionP10Si)
                    .addComponent(opcionP10No)
                    .addComponent(opcionP10NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP11)
                    .addComponent(opcionP11Si)
                    .addComponent(opcionP11No)
                    .addComponent(opcionP11NA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etP12)
                    .addComponent(opcionP12Si)
                    .addComponent(opcionP12No)
                    .addComponent(opcionP12NA)))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TITULO");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonRespuesta.setText("Siguiente");

        botonLimpiarOpciones.setText("Reiniciar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPreguntas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonLimpiarOpciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRespuesta)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRespuesta)
                    .addComponent(botonLimpiarOpciones))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLimpiarOpciones;
    private javax.swing.JButton botonRespuesta;
    private javax.swing.JLabel etP1;
    private javax.swing.JLabel etP10;
    private javax.swing.JLabel etP11;
    private javax.swing.JLabel etP12;
    private javax.swing.JLabel etP2;
    private javax.swing.JLabel etP3;
    private javax.swing.JLabel etP4;
    private javax.swing.JLabel etP5;
    private javax.swing.JLabel etP6;
    private javax.swing.JLabel etP7;
    private javax.swing.JLabel etP8;
    private javax.swing.JLabel etP9;
    private javax.swing.ButtonGroup grupoP1;
    private javax.swing.ButtonGroup grupoP10;
    private javax.swing.ButtonGroup grupoP11;
    private javax.swing.ButtonGroup grupoP12;
    private javax.swing.ButtonGroup grupoP2;
    private javax.swing.ButtonGroup grupoP3;
    private javax.swing.ButtonGroup grupoP4;
    private javax.swing.ButtonGroup grupoP5;
    private javax.swing.ButtonGroup grupoP6;
    private javax.swing.ButtonGroup grupoP7;
    private javax.swing.ButtonGroup grupoP8;
    private javax.swing.ButtonGroup grupoP9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton opcionP10NA;
    private javax.swing.JRadioButton opcionP10No;
    private javax.swing.JRadioButton opcionP10Si;
    private javax.swing.JRadioButton opcionP11NA;
    private javax.swing.JRadioButton opcionP11No;
    private javax.swing.JRadioButton opcionP11Si;
    private javax.swing.JRadioButton opcionP12NA;
    private javax.swing.JRadioButton opcionP12No;
    private javax.swing.JRadioButton opcionP12Si;
    private javax.swing.JRadioButton opcionP1NA;
    private javax.swing.JRadioButton opcionP1No;
    private javax.swing.JRadioButton opcionP1Si;
    private javax.swing.JRadioButton opcionP2NA;
    private javax.swing.JRadioButton opcionP2No;
    private javax.swing.JRadioButton opcionP2Si;
    private javax.swing.JRadioButton opcionP3NA;
    private javax.swing.JRadioButton opcionP3No;
    private javax.swing.JRadioButton opcionP3Si;
    private javax.swing.JRadioButton opcionP4NA;
    private javax.swing.JRadioButton opcionP4No;
    private javax.swing.JRadioButton opcionP4Si;
    private javax.swing.JRadioButton opcionP5No;
    private javax.swing.JRadioButton opcionP5Si;
    private javax.swing.JRadioButton opcionP6NA;
    private javax.swing.JRadioButton opcionP6No;
    private javax.swing.JRadioButton opcionP6Si;
    private javax.swing.JRadioButton opcionP7NA;
    private javax.swing.JRadioButton opcionP7No;
    private javax.swing.JRadioButton opcionP7Si;
    private javax.swing.JRadioButton opcionP8NA;
    private javax.swing.JRadioButton opcionP8No;
    private javax.swing.JRadioButton opcionP8Si;
    private javax.swing.JRadioButton opcionP9NA;
    private javax.swing.JRadioButton opcionP9No;
    private javax.swing.JRadioButton opcionP9Si;
    private javax.swing.JRadioButton opciónP5NA;
    private javax.swing.JPanel panelPreguntas;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
